spring:
  datasource:
    url: jdbc:mysql://localhost:3306/askanything?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  security:
    user:
      name: user
      password: user
  sql:
    init:
      enabled: true
  profiles:
    active: dev